sudo: required

language: go
go_import_path: github.com/ethereum/go-ethereum

services:
  - docker

before_install:
  - docker build -t enapoleone/tomochain .
  - docker run enapoleone/tomochain

jobs:
  include:
  - stage: Build and test
    os: linux
    dist: trusty
    sudo: required
    go: 1.9.x
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - go run build/ci.go test -coverage
  - os: linux
    dist: trusty
    sudo: required
    go: '1.10'
    script:
    - sudo modprobe fuse
    - sudo chmod 666 /dev/fuse
    - sudo chown root:$USER /etc/fuse.conf
    - go run build/ci.go install
    - go run build/ci.go test -coverage
  - os: osx
    go: '1.10'
    script:
    - unset -f cd
    - brew update
    - brew cask install osxfuse
    - go run build/ci.go install
    - go run build/ci.go test -coverage
  - stage: Lint
    os: linux
    dist: trusty
    go: '1.10'
    env:
    - lint
    git:
      submodules: false
    script:
    - go run build/ci.go lint
  - stage: Push Docker image
    deploy:
      provider: script
      script: bash docker_push
      on:
        branch: travis
