repository: ethereum/go-ethereum

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

favicon: /static/images/favicon.png

defaults:
  -
    scope:
      path: ""
    values:
      layout: sidebar

collections_dir: docs
collections:
  install-and-build:
    output: true
    caption: Install and build
    sidebar: true
  how-to:
    output: true
    caption: How to use
    sidebar: true
  interface:
    output: true
    caption: Interface documentation
    sidebar: true
  support:
    output: true
    caption: Issues and support
    sidebar: true
  developers:
    output: true
    caption: Developers
    sidebar: true
