repository: ethereum/go-ethereum
google_analytics: UA-131485733-1
#remote_theme: Phlow/feeling-responsive
remote_theme: daattali/beautiful-jekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore
layout: page
avatar: /static/images/ethereum.png
author:
  name: The go-ethereum authors
navbar-links:
  Install and build:
    - Downloads: downloads
    - Installing Ethereum: docs/Building-Ethereum
    - Developers' Guide: docs/Developers%27-Guide
  How to use:
    - Managing Accounts: docs/Managing-your-accounts
    - Mining: docs/Mining
    - Contract Tutorial: docs/Contract-Tutorial
  Interface Documentation:
    - Command Line Options: docs/Command-Line-Options
    - JavaScript Console: docs/JavaScript-Console
    - Management API: docs/Management-APIs
    - JSON-RPC server: https://github.com/ethereum/wiki/wiki/JSON-RPC
  Issues and support:
    - FAQ: docs/FAQ
    - Reporting issues: docs/geth#reporting
    - Community and support: docs/geth#community-and-support
    - Issue handling workflow: docs/Issue-handling-workflow
  Developers:
    - Mobile Clients: docs/Mobile-Clients/Libraries-and-Inproc-Ethereum-Nodes
    - Native DApps: docs/Native-DApps/Go-bindings-to-Ethereum-contracts
    - Active go-ethereum projects: docs/Active-go-ethereum-projects
  Swarm and friends:
    - TODO: docs/Swarm---TODO
    - distributed preimage archive: docs/Swarm---distributed-preimage-archive
    - Channels, Namereg-resolution: docs/Swarm-Channels,-Namereg-resolution-draft
    - Contract: docs/Swarm-Contract
    - POC series: docs/swarm---POC-series
    - dev progress: docs/swarm-dev-progress
    - roadmap: docs/swarm-roadmap
  Other docs:
    - Accounts key-storage specification: docs/Accounts---key-storage-specification
    - Connecting to the network: docs/Connecting-to-the-network
    - Creating your own Ethereum apps using Eth go: docs/Creating-your-own-Ethereum-apps-using-Eth-go
    - Developer guide: docs/Developer-Guide
    - Disclaimer: docs/Disclaimer
    - Ethereum Specification: docs/Ethereum-Specification
    - Ethereum on Android: docs/Ethereum-on-Android
    - GAs Price Oracle: docs/Gas-Price-Oracle
    - Go ethereum management API's: docs/Go-ethereum-management-API's
    - IPFS & SWARM: docs/IPFS-&-SWARM
    - Installing Geth: docs/Installing-Geth
    - \[Japanese\] Contracts and Transactions: docs/[Japanese]-Contracts-and-Transactions
    - Provisional JS API: docs/Provisional-JS-API
    - RPC PUB-SUB: docs/RPC-PUB-SUB
    - Sending ethere: docs/Sending-ether
    - Setting up Ethereum (Native): docs/Setting-up-Ethereum-(Native)
    - URL Scheme: docs/URL-Scheme