repository: ethereum/go-ethereum

exclude:
  - Gemfile
  - Gemfile.lock
  - .gitignore

favicon: /static/images/favicon.png

defaults:
  -
    scope:
      path: ""
    values:
      layout: sidebar

collections_dir: docs
collections:
  install-and-build:
    output: true
    caption: Install and build
    sidebar: true
  Mobile:
    output: true
    caption: Mobile-related
    sidebar: true