os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: c:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GOPATH: c:\gopath

install:
  - go version
  - cd c:\gopath\src\github.com\ethereum\go-ethereum
  - set MSYSTEM=MINGW64
  - C:\msys64\usr\bin\bash -l -c "gcc --version"

build_script:
  - C:\msys64\usr\bin\bash -l -c "go run build/ci.go install"

test_script:
  - C:\msys64\usr\bin\bash -l -c "go run build/ci.go test -vet -coverage"

after_build:
  - go run build\ci.go archive -type zip

artifacts:
  - path: geth-*.zip
