os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: c:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GOPATH: c:\gopath
    # MinGW and Go are preinstalled. Go is already in PATH.
    PATH: c:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin:%PATH%

install:
  - cd c:\gopath\src\github.com\ethereum\go-ethereum
  - dir c:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw32\bin
  - echo %PATH%
  - go version
  - gcc --version

build_script:
  - go run build\ci.go install

test_script:
  - go run build\ci.go test -vet -coverage

after_build:
  - go run build\ci.go archive -type zip

artifacts:
  - path: geth-*.zip
