os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: c:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GOPATH: c:\gopath
    PATH: c:\mingw\bin;%PATH%

install:
  - c:\go-x86\go version
  - gcc --version

build_script:
  - c:\go-x86\go run build\ci.go install

test_script:
  - c:\go-x86\go run build\ci.go test -vet -coverage

after_build:
  - c:\go-x86\go run build\ci.go archive -type zip

artifacts:
  - path: geth-*.zip
