os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: c:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GOPATH: c:\gopath
    CC: clang

install:
  - cd c:\gopath\src\github.com\ethereum\go-ethereum
  - go version
  - clang --version

build_script:
  - go run build\ci.go install

test_script:
  - go run build\ci.go test -vet -coverage

after_build:
  - go run build\ci.go archive -type zip

artifacts:
  - path: geth-*.zip
