os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: c:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    # Go stuff
    GOPATH: c:\gopath
    GO: c:\go\bin\go
    GOROOT: c:\go
    # MSYS2 stuff
    MSYS2_ARCH: x86_64
    MSYSTEM: MINGW64
    PATH: C:\msys64\%MSYSTEM%\bin;C:\msys64\usr\bin;%PATH%

install:
  - "%GO% version"
  # Update MSYS2
  # - bash -lc "pacman --noconfirm --sync --refresh --refresh pacman"
  # - bash -lc "pacman --noconfirm --sync --refresh --refresh --sysupgrade --sysupgrade"
  # Install MinGW gcc
  - bash -lc "pacman --noconfirm -S mingw-w64-gcc"
  - gcc --version

build_script:
  - "%GO% run build\\ci.go install"

test_script:
  - "%GO% run build\\ci.go test -vet -coverage"

after_build:
  - "%GO% run build\\ci.go archive -type zip"

artifacts:
  - path: geth-*.zip
