os: Visual Studio 2015

# Clone directly into GOPATH.
clone_folder: c:\gopath\src\github.com\ethereum\go-ethereum
clone_depth: 5
version: "{branch}.{build}"
environment:
  global:
    GOPATH: c:\gopath
    PATH: c:\mingw\bin;%PATH%
    GO: c:\go-x86\bin\go
    GOROOT: c:\go-x86

install:
  - "%GO% version"
  - gcc --version

build_script:
  - "%GO% run build\\ci.go install"

test_script:
  - "%GO% run build\\ci.go test -vet -coverage"

after_build:
  - "%GO% run build\\ci.go archive -type zip"

artifacts:
  - path: geth-*.zip
