 version: '3'

 services:
  shyftgeth:
    build:
      context: $PWD 
      dockerfile: containers/docker/develop-alpine/shyftGeth/Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30301:30301"
      - "30303:30303/udp"
      - "30304:30304"
      - "5432:5432"
    volumes:
      - .:/go/src/ShyftNetwork/go-empyrean
    working_dir: /go/src/ShyftNetwork/go-empyrean
    depends_on: 
      - pg
  pg:
    build: 
      context: $PWD
      dockerfile: containers/docker/develop-alpine/pg/Dockerfile
    volumes:
      - ./pg-data:/var/lib/postgresql/data
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSGRES_PASSWORD=docker
      - PGDATA=/pg-data
  
  

  # api:
  #   build:
  #     context: ./containers/docker/develop-alpine/shyftApi


